export const postExamle = {
  Countries: [
    {
      id: "0",
      code: "248",
      name: "Aland adaları",
      abbreviation2: "AX",
      abbreviation3: "ALA",
    },
    {
      id: "0",
      code: "008",
      name: "Albaniya",
      abbreviation2: "AL",
      abbreviation3: "ALB",
    },
    {
      id: "0",
      code: "276",
      name: "Almaniya",
      abbreviation2: "DE",
      abbreviation3: "DEU",
    },
    {
      id: "0",
      code: "840",
      name: "Amerika Birləşmiş Ştatları",
      abbreviation2: "US",
      abbreviation3: "USA",
    },
    {
      id: "0",
      code: "016",
      name: "Amerika Samoası",
      abbreviation2: "AS",
      abbreviation3: "ASM",
    },
    {
      id: "0",
      code: "020",
      name: "Andorra",
      abbreviation2: "AD",
      abbreviation3: "AND",
    },
    {
      id: "0",
      code: "660",
      name: "Anqilya (Britaniya)",
      abbreviation2: "AI",
      abbreviation3: "AIA",
    },
    {
      id: "0",
      code: "024",
      name: "Anqola",
      abbreviation2: "AO",
      abbreviation3: "AGO",
    },
    {
      id: "0",
      code: "028",
      name: "Antiqua və Barbuda",
      abbreviation2: "AG",
      abbreviation3: "ATG",
    },
    {
      id: "0",
      code: "032",
      name: "Argentina",
      abbreviation2: "AR",
      abbreviation3: "ARG",
    },
    {
      id: "0",
      code: "533",
      name: "Aruba",
      abbreviation2: "AW",
      abbreviation3: "ABW",
    },
    {
      id: "0",
      code: "036",
      name: "Avstraliya",
      abbreviation2: "AU",
      abbreviation3: "AUS",
    },
    {
      id: "0",
      code: "040",
      name: "Avstriya",
      abbreviation2: "AT",
      abbreviation3: "AUT",
    },
    {
      id: "0",
      code: "031",
      name: "Azərbaycan",
      abbreviation2: "AZ",
      abbreviation3: "AZE",
    },
    {
      id: "0",
      code: "044",
      name: "Baham adaları",
      abbreviation2: "BS",
      abbreviation3: "BHS",
    },
    {
      id: "0",
      code: "050",
      name: "Banqladeş",
      abbreviation2: "BD",
      abbreviation3: "BGD",
    },
    {
      id: "0",
      code: "052",
      name: "Barbados",
      abbreviation2: "BB",
      abbreviation3: "BRB",
    },
    {
      id: "0",
      code: "112",
      name: "Belarus",
      abbreviation2: "BY",
      abbreviation3: "BLR",
    },
    {
      id: "0",
      code: "084",
      name: "Beliz",
      abbreviation2: "BZ",
      abbreviation3: "BLZ",
    },
    {
      id: "0",
      code: "056",
      name: "Belçika",
      abbreviation2: "BE",
      abbreviation3: "BEL",
    },
    {
      id: "0",
      code: "204",
      name: "Benin",
      abbreviation2: "BJ",
      abbreviation3: "BEN",
    },
    {
      id: "0",
      code: "060",
      name: "Bermud adaları",
      abbreviation2: "BM",
      abbreviation3: "BMU",
    },
    {
      id: "0",
      code: "000",
      name: "Bilinmir",
      abbreviation2: "XX",
      abbreviation3: "XXX",
    },
    {
      id: "0",
      code: "784",
      name: "Birləşmiş Ərəb Əmirlikləri",
      abbreviation2: "AE",
      abbreviation3: "ARE",
    },
    {
      id: "0",
      code: "068",
      name: "Boliviya",
      abbreviation2: "BO",
      abbreviation3: "BOL",
    },
    {
      id: "0",
      code: "100",
      name: "Bolqarıstan",
      abbreviation2: "BG",
      abbreviation3: "BGR",
    },
    {
      id: "0",
      code: "535",
      name: "Boneyr, Sint-Estatius və Saba",
      abbreviation2: " -",
      abbreviation3: "BES",
    },
    {
      id: "0",
      code: "070",
      name: "Bosniya və Herseqovina",
      abbreviation2: "BA",
      abbreviation3: "BIH",
    },
    {
      id: "0",
      code: "072",
      name: "Botsvana",
      abbreviation2: "BW",
      abbreviation3: "BWA",
    },
    {
      id: "0",
      code: "076",
      name: "Braziliya",
      abbreviation2: "BR",
      abbreviation3: "BRA",
    },
    {
      id: "0",
      code: "096",
      name: "Bruney-Darüssalam",
      abbreviation2: "BN",
      abbreviation3: "BRN",
    },
    {
      id: "0",
      code: "854",
      name: "Burkina-Faso",
      abbreviation2: "BF",
      abbreviation3: "BFA",
    },
    {
      id: "0",
      code: "108",
      name: "Burundi",
      abbreviation2: "BI",
      abbreviation3: "BDI",
    },
    {
      id: "0",
      code: "064",
      name: "Butan",
      abbreviation2: "BT",
      abbreviation3: "BTN",
    },
    {
      id: "0",
      code: "826",
      name: "Böyük Britaniya",
      abbreviation2: "GB",
      abbreviation3: "GBR",
    },
    {
      id: "0",
      code: "048",
      name: "Bəhreyn",
      abbreviation2: "BH",
      abbreviation3: "BHR",
    },
    {
      id: "0",
      code: "832",
      name: "Cersi adası",
      abbreviation2: "JE",
      abbreviation3: "JEY",
    },
    {
      id: "0",
      code: "262",
      name: "Cibuti",
      abbreviation2: "DJ",
      abbreviation3: "DJI",
    },
    {
      id: "0",
      code: "292",
      name: "Cəbəli-Tariq",
      abbreviation2: "GI",
      abbreviation3: "GIB",
    },
    {
      id: "0",
      code: "710",
      name: "Cənubi Afrika Respublikası",
      abbreviation2: "ZA",
      abbreviation3: "ZAF",
    },
    {
      id: "0",
      code: "728",
      name: "Cənubi Sudan",
      abbreviation2: "SS",
      abbreviation3: "SSD",
    },
    {
      id: "0",
      code: "208",
      name: "Danimarka",
      abbreviation2: "DK",
      abbreviation3: "DNK",
    },
    {
      id: "0",
      code: "212",
      name: "Dominika",
      abbreviation2: "DM",
      abbreviation3: "DMA",
    },
    {
      id: "0",
      code: "214",
      name: "Dominikan Respublikası",
      abbreviation2: "DO",
      abbreviation3: "DOM",
    },
    {
      id: "0",
      code: "218",
      name: "Ekvador",
      abbreviation2: "EC",
      abbreviation3: "ECU",
    },
    {
      id: "0",
      code: "226",
      name: "Ekvatorial Qvineya",
      abbreviation2: "GQ",
      abbreviation3: "GNQ",
    },
    {
      id: "0",
      code: "232",
      name: "Eritreya",
      abbreviation2: "ER",
      abbreviation3: "ERI",
    },
    {
      id: "0",
      code: "051",
      name: "Ermənistan",
      abbreviation2: "AM",
      abbreviation3: "ARM",
    },
    {
      id: "0",
      code: "233",
      name: "Estoniya",
      abbreviation2: "EE",
      abbreviation3: "EST",
    },
    {
      id: "0",
      code: "234",
      name: "Farer adaları",
      abbreviation2: "FO",
      abbreviation3: "FRO",
    },
    {
      id: "0",
      code: "242",
      name: "Fici",
      abbreviation2: "FJ",
      abbreviation3: "FJI",
    },
    {
      id: "0",
      code: "608",
      name: "Filippinlər",
      abbreviation2: "PH",
      abbreviation3: "PHL",
    },
    {
      id: "0",
      code: "246",
      name: "Finlandiya",
      abbreviation2: "FI",
      abbreviation3: "FIN",
    },
    {
      id: "0",
      code: "238",
      name: "Folklend (Malvin) adaları",
      abbreviation2: "FK",
      abbreviation3: "FLK",
    },
    {
      id: "0",
      code: "250",
      name: "Fransa",
      abbreviation2: "FR",
      abbreviation3: "FRA",
    },
    {
      id: "0",
      code: "258",
      name: "Fransa Polineziyası",
      abbreviation2: "PF",
      abbreviation3: "PYF",
    },
    {
      id: "0",
      code: "254",
      name: "Fransa Qvianası",
      abbreviation2: "GF",
      abbreviation3: "GUF",
    },
    {
      id: "0",
      code: "275",
      name: "Fələstin",
      abbreviation2: "PS",
      abbreviation3: "PSE",
    },
    {
      id: "0",
      code: "268",
      name: "Gürcüstan",
      abbreviation2: "GE",
      abbreviation3: "GEO",
    },
    {
      id: "0",
      code: "332",
      name: "Haiti",
      abbreviation2: "HT",
      abbreviation3: "HTI",
    },
    {
      id: "0",
      code: "831",
      name: "Hernsi adası",
      abbreviation2: "GG",
      abbreviation3: "GGY",
    },
    {
      id: "0",
      code: "356",
      name: "Hindistan",
      abbreviation2: "IN",
      abbreviation3: "IND",
    },
    {
      id: "0",
      code: "340",
      name: "Honduras",
      abbreviation2: "HN",
      abbreviation3: "HND",
    },
    {
      id: "0",
      code: "231",
      name: "Həbəşistan",
      abbreviation2: "ET",
      abbreviation3: "ETH",
    },
    {
      id: "0",
      code: "132",
      name: "Kabo-Verde",
      abbreviation2: "CV",
      abbreviation3: "CPV",
    },
    {
      id: "0",
      code: "116",
      name: "Kamboca",
      abbreviation2: "KH",
      abbreviation3: "KHM",
    },
    {
      id: "0",
      code: "120",
      name: "Kamerun",
      abbreviation2: "CM",
      abbreviation3: "CMR",
    },
    {
      id: "0",
      code: "124",
      name: "Kanada",
      abbreviation2: "CA",
      abbreviation3: "CAN",
    },
    {
      id: "0",
      code: "136",
      name: "Kayman adaları",
      abbreviation2: "KY",
      abbreviation3: "CYM",
    },
    {
      id: "0",
      code: "404",
      name: "Keniya",
      abbreviation2: "KE",
      abbreviation3: "KEN",
    },
    {
      id: "0",
      code: "807",
      name: "Keç. Yuq. Resp. Makedoniya",
      abbreviation2: "MK",
      abbreviation3: "MKD",
    },
    {
      id: "0",
      code: "196",
      name: "Kipr",
      abbreviation2: "CY",
      abbreviation3: "CYP",
    },
    {
      id: "0",
      code: "296",
      name: "Kiribati",
      abbreviation2: "KI",
      abbreviation3: "KIR",
    },
    {
      id: "0",
      code: "170",
      name: "Kolumbiya",
      abbreviation2: "CO",
      abbreviation3: "COL",
    },
    {
      id: "0",
      code: "178",
      name: "Konqo (Brazzavil)",
      abbreviation2: "CG",
      abbreviation3: "COG",
    },
    {
      id: "0",
      code: "180",
      name: "Konqo (Kinşasa)",
      abbreviation2: "CD",
      abbreviation3: "COD",
    },
    {
      id: "0",
      code: "408",
      name: "Koreya (KXDR)",
      abbreviation2: "KP",
      abbreviation3: "PRK",
    },
    {
      id: "0",
      code: "410",
      name: "Koreya Respublikası",
      abbreviation2: "KR",
      abbreviation3: "KOR",
    },
    {
      id: "0",
      code: "188",
      name: "Kosta-Rika",
      abbreviation2: "CR",
      abbreviation3: "CRI",
    },
    {
      id: "0",
      code: "384",
      name: "Kot-divuar",
      abbreviation2: "CI",
      abbreviation3: "CIV",
    },
    {
      id: "0",
      code: "192",
      name: "Kuba",
      abbreviation2: "CU",
      abbreviation3: "CUB",
    },
    {
      id: "0",
      code: "184",
      name: "Kuk adaları (Yeni Zelanda)",
      abbreviation2: "CK",
      abbreviation3: "COK",
    },
    {
      id: "0",
      code: "531",
      name: "Kurasao",
      abbreviation2: "CW",
      abbreviation3: "CUW",
    },
    {
      id: "0",
      code: "414",
      name: "Küveyt",
      abbreviation2: "KW",
      abbreviation3: "KWT",
    },
    {
      id: "0",
      code: "418",
      name: "Laos (LXDR)",
      abbreviation2: "LA",
      abbreviation3: "LAO",
    },
    {
      id: "0",
      code: "428",
      name: "Latviya",
      abbreviation2: "LV",
      abbreviation3: "LVA",
    },
    {
      id: "0",
      code: "426",
      name: "Lesoto",
      abbreviation2: "LS",
      abbreviation3: "LSO",
    },
    {
      id: "0",
      code: "430",
      name: "Liberiya",
      abbreviation2: "LR",
      abbreviation3: "LBR",
    },
    {
      id: "0",
      code: "440",
      name: "Litva",
      abbreviation2: "LT",
      abbreviation3: "LTU",
    },
    {
      id: "0",
      code: "422",
      name: "Livan",
      abbreviation2: "LB",
      abbreviation3: "LBN",
    },
    {
      id: "0",
      code: "434",
      name: "Liviya",
      abbreviation2: "LY",
      abbreviation3: "LBY",
    },
    {
      id: "0",
      code: "438",
      name: "Lixtenşteyn",
      abbreviation2: "LI",
      abbreviation3: "LIE",
    },
    {
      id: "0",
      code: "442",
      name: "Lüksemburq",
      abbreviation2: "LU",
      abbreviation3: "LUX",
    },
    {
      id: "0",
      code: "348",
      name: "Macarıstan",
      abbreviation2: "HU",
      abbreviation3: "HUN",
    },
    {
      id: "0",
      code: "450",
      name: "Madaqaskar",
      abbreviation2: "MG",
      abbreviation3: "MDG",
    },
    {
      id: "0",
      code: "454",
      name: "Malavi",
      abbreviation2: "MW",
      abbreviation3: "MWI",
    },
    {
      id: "0",
      code: "458",
      name: "Malayziya",
      abbreviation2: "MY",
      abbreviation3: "MYS",
    },
    {
      id: "0",
      code: "462",
      name: "Maldiv adaları",
      abbreviation2: "MV",
      abbreviation3: "MDV",
    },
    {
      id: "0",
      code: "466",
      name: "Mali",
      abbreviation2: "ML",
      abbreviation3: "MLI",
    },
    {
      id: "0",
      code: "470",
      name: "Malta",
      abbreviation2: "MT",
      abbreviation3: "MLT",
    },
    {
      id: "0",
      code: "175",
      name: "Maori (Mayotta)",
      abbreviation2: "YT",
      abbreviation3: "MYT",
    },
    {
      id: "0",
      code: "474",
      name: "Martinika ",
      abbreviation2: "MQ",
      abbreviation3: "MTQ",
    },
    {
      id: "0",
      code: "584",
      name: "Marşal adaları",
      abbreviation2: "MH",
      abbreviation3: "MHL",
    },
    {
      id: "0",
      code: "480",
      name: "Mavriki",
      abbreviation2: "MU",
      abbreviation3: "MUS",
    },
    {
      id: "0",
      code: "478",
      name: "Mavritaniya",
      abbreviation2: "MR",
      abbreviation3: "MRT",
    },
    {
      id: "0",
      code: "484",
      name: "Meksika",
      abbreviation2: "MX",
      abbreviation3: "MEX",
    },
    {
      id: "0",
      code: "833",
      name: "Men adası",
      abbreviation2: "IM",
      abbreviation3: "IMN",
    },
    {
      id: "0",
      code: "583",
      name: "Mikroneziya",
      abbreviation2: "FM",
      abbreviation3: "FSM",
    },
    {
      id: "0",
      code: "818",
      name: "Misir",
      abbreviation2: "EG",
      abbreviation3: "EGY",
    },
    {
      id: "0",
      code: "498",
      name: "Moldova",
      abbreviation2: "MD",
      abbreviation3: "MDA",
    },
    {
      id: "0",
      code: "492",
      name: "Monako",
      abbreviation2: "MC",
      abbreviation3: "MCO",
    },
    {
      id: "0",
      code: "496",
      name: "Monqolustan",
      abbreviation2: "MN",
      abbreviation3: "MNG",
    },
    {
      id: "0",
      code: "499",
      name: "Monteneqro",
      abbreviation2: "ME",
      abbreviation3: "MNE",
    },
    {
      id: "0",
      code: "500",
      name: "Montserrat",
      abbreviation2: "MS",
      abbreviation3: "MSR",
    },
    {
      id: "0",
      code: "508",
      name: "Mozambik",
      abbreviation2: "MZ",
      abbreviation3: "MOZ",
    },
    {
      id: "0",
      code: "104",
      name: "Myanma",
      abbreviation2: "MM",
      abbreviation3: "MMR",
    },
    {
      id: "0",
      code: "654",
      name: "Müqəddəs Yelena Adası",
      abbreviation2: "SH",
      abbreviation3: "SHN",
    },
    {
      id: "0",
      code: "001",
      name: "Müxtəlif",
      abbreviation2: "XX",
      abbreviation3: "XXX",
    },
    {
      id: "0",
      code: "504",
      name: "Mərakeş",
      abbreviation2: "MA",
      abbreviation3: "MAR",
    },
    {
      id: "0",
      code: "140",
      name: "Mərkəzi Afrika Respublikası ",
      abbreviation2: "CF",
      abbreviation3: "CAF",
    },
    {
      id: "0",
      code: "516",
      name: "Namibiya",
      abbreviation2: "NA",
      abbreviation3: "NAM",
    },
    {
      id: "0",
      code: "520",
      name: "Nauru",
      abbreviation2: "NR",
      abbreviation3: "NRU",
    },
    {
      id: "0",
      code: "524",
      name: "Nepal",
      abbreviation2: "NP",
      abbreviation3: "NPL",
    },
    {
      id: "0",
      code: "528",
      name: "Niderland",
      abbreviation2: "NL",
      abbreviation3: "NLD",
    },
    {
      id: "0",
      code: "562",
      name: "Niger",
      abbreviation2: "NE",
      abbreviation3: "NER",
    },
    {
      id: "0",
      code: "566",
      name: "Nigeriya",
      abbreviation2: "NG",
      abbreviation3: "NGA",
    },
    {
      id: "0",
      code: "558",
      name: "Nikaraqua",
      abbreviation2: "NI",
      abbreviation3: "NIC",
    },
    {
      id: "0",
      code: "570",
      name: "Niue (Yeni Zelanda)",
      abbreviation2: "NU",
      abbreviation3: "NIU",
    },
    {
      id: "0",
      code: "574",
      name: "Norfolk adası (Avstraliya)",
      abbreviation2: "NF",
      abbreviation3: "NFK",
    },
    {
      id: "0",
      code: "830",
      name: "Normand adaları",
      abbreviation2: "  ",
      abbreviation3: "   ",
    },
    {
      id: "0",
      code: "578",
      name: "Norveç",
      abbreviation2: "NO",
      abbreviation3: "NOR",
    },
    {
      id: "0",
      code: "512",
      name: "Oman",
      abbreviation2: "OM",
      abbreviation3: "OMN",
    },
    {
      id: "0",
      code: "586",
      name: "Pakistan",
      abbreviation2: "PK",
      abbreviation3: "PAK",
    },
    {
      id: "0",
      code: "585",
      name: "Palau",
      abbreviation2: "PW",
      abbreviation3: "PLW",
    },
    {
      id: "0",
      code: "591",
      name: "Panama",
      abbreviation2: "PA",
      abbreviation3: "PAN",
    },
    {
      id: "0",
      code: "598",
      name: "Papua-Yeni Qvineya",
      abbreviation2: "PG",
      abbreviation3: "PNG",
    },
    {
      id: "0",
      code: "600",
      name: "Paraqvay",
      abbreviation2: "PY",
      abbreviation3: "PRY",
    },
    {
      id: "0",
      code: "604",
      name: "Peru",
      abbreviation2: "PE",
      abbreviation3: "PER",
    },
    {
      id: "0",
      code: "612",
      name: "Pitkern (Britaniya)",
      abbreviation2: "PN",
      abbreviation3: "PCN",
    },
    {
      id: "0",
      code: "616",
      name: "Polşa",
      abbreviation2: "PL",
      abbreviation3: "POL",
    },
    {
      id: "0",
      code: "620",
      name: "Portuqaliya",
      abbreviation2: "PT",
      abbreviation3: "PRT",
    },
    {
      id: "0",
      code: "630",
      name: "Puerto-Riko (ABŞ)",
      abbreviation2: "PR",
      abbreviation3: "PRI",
    },
    {
      id: "0",
      code: "266",
      name: "Qabon",
      abbreviation2: "GA",
      abbreviation3: "GAB",
    },
    {
      id: "0",
      code: "270",
      name: "Qambiya",
      abbreviation2: "GM",
      abbreviation3: "GMB",
    },
    {
      id: "0",
      code: "288",
      name: "Qana",
      abbreviation2: "GH",
      abbreviation3: "GHA",
    },
    {
      id: "0",
      code: "328",
      name: "Qayana",
      abbreviation2: "GY",
      abbreviation3: "GUY",
    },
    {
      id: "0",
      code: "398",
      name: "Qazaxıstan",
      abbreviation2: "KZ",
      abbreviation3: "KAZ",
    },
    {
      id: "0",
      code: "308",
      name: "Qrenada",
      abbreviation2: "GD",
      abbreviation3: "GRD",
    },
    {
      id: "0",
      code: "304",
      name: "Qrenlandiya",
      abbreviation2: "GL",
      abbreviation3: "GRL",
    },
    {
      id: "0",
      code: "316",
      name: "Quam (ABŞ)",
      abbreviation2: "GU",
      abbreviation3: "GUM",
    },
    {
      id: "0",
      code: "312",
      name: "Qvadelupa (Fransa)",
      abbreviation2: "GP",
      abbreviation3: "GLP",
    },
    {
      id: "0",
      code: "320",
      name: "Qvatemala",
      abbreviation2: "GT",
      abbreviation3: "GTM",
    },
    {
      id: "0",
      code: "324",
      name: "Qvineya",
      abbreviation2: "GN",
      abbreviation3: "GIN",
    },
    {
      id: "0",
      code: "624",
      name: "Qvineya-Bissau",
      abbreviation2: "GW",
      abbreviation3: "GNB",
    },
    {
      id: "0",
      code: "417",
      name: "Qırğızıstan",
      abbreviation2: "KG",
      abbreviation3: "KGZ",
    },
    {
      id: "0",
      code: "174",
      name: "Qəmər adaları",
      abbreviation2: "KM",
      abbreviation3: "COM",
    },
    {
      id: "0",
      code: "732",
      name: "Qərbi Sahara",
      abbreviation2: "EH",
      abbreviation3: "ESH",
    },
    {
      id: "0",
      code: "634",
      name: "Qətər",
      abbreviation2: "QA",
      abbreviation3: "QAT",
    },
    {
      id: "0",
      code: "638",
      name: "Reyunyon (Fransa)",
      abbreviation2: "RE",
      abbreviation3: "REU",
    },
    {
      id: "0",
      code: "646",
      name: "Ruanda",
      abbreviation2: "RW",
      abbreviation3: "RWA",
    },
    {
      id: "0",
      code: "642",
      name: "Rumıniya",
      abbreviation2: "RO",
      abbreviation3: "ROU",
    },
    {
      id: "0",
      code: "643",
      name: "Rusiya",
      abbreviation2: "RU",
      abbreviation3: "RUS",
    },
    {
      id: "0",
      code: "222",
      name: "Salvador",
      abbreviation2: "SV",
      abbreviation3: "SLV",
    },
    {
      id: "0",
      code: "882",
      name: "Samoa",
      abbreviation2: "WS",
      abbreviation3: "WSM",
    },
    {
      id: "0",
      code: "674",
      name: "San-Marino",
      abbreviation2: "SM",
      abbreviation3: "SMR",
    },
    {
      id: "0",
      code: "678",
      name: "San-Tome və Prinsipi ",
      abbreviation2: "ST",
      abbreviation3: "STP",
    },
    {
      id: "0",
      code: "652",
      name: "Sen-Bartelemi",
      abbreviation2: "BL",
      abbreviation3: "BLM",
    },
    {
      id: "0",
      code: "663",
      name: "Sen-Marten (Fransa)",
      abbreviation2: "MF",
      abbreviation3: "MAF",
    },
    {
      id: "0",
      code: "534",
      name: "Sen-Marten (Niderland)",
      abbreviation2: "SX",
      abbreviation3: "SXM",
    },
    {
      id: "0",
      code: "666",
      name: "Sen-Pyer və Mikelon",
      abbreviation2: "PM",
      abbreviation3: "SPM",
    },
    {
      id: "0",
      code: "686",
      name: "Seneqal",
      abbreviation2: "SN",
      abbreviation3: "SEN",
    },
    {
      id: "0",
      code: "659",
      name: "Sent-Kits və Nevis",
      abbreviation2: "KN",
      abbreviation3: "KNA",
    },
    {
      id: "0",
      code: "662",
      name: "Sent-Lüsiya",
      abbreviation2: "LC",
      abbreviation3: "LCA",
    },
    {
      id: "0",
      code: "670",
      name: "Sent-Vinsent və Qrenadina",
      abbreviation2: "VC",
      abbreviation3: "VCT",
    },
    {
      id: "0",
      code: "688",
      name: "Serbiya",
      abbreviation2: "RS",
      abbreviation3: "SRB",
    },
    {
      id: "0",
      code: "690",
      name: "Seyşel adaları",
      abbreviation2: "SC",
      abbreviation3: "SYC",
    },
    {
      id: "0",
      code: "702",
      name: "Sinqapur",
      abbreviation2: "SG",
      abbreviation3: "SGP",
    },
    {
      id: "0",
      code: "703",
      name: "Slovakiya",
      abbreviation2: "SK",
      abbreviation3: "SVK",
    },
    {
      id: "0",
      code: "705",
      name: "Sloveniya",
      abbreviation2: "SI",
      abbreviation3: "SVN",
    },
    {
      id: "0",
      code: "090",
      name: "Solomon adaları",
      abbreviation2: "SB",
      abbreviation3: "SLB",
    },
    {
      id: "0",
      code: "706",
      name: "Somali",
      abbreviation2: "SO",
      abbreviation3: "SOM",
    },
    {
      id: "0",
      code: "729",
      name: "Sudan",
      abbreviation2: "SD",
      abbreviation3: "SDN",
    },
    {
      id: "0",
      code: "740",
      name: "Surinam",
      abbreviation2: "SR",
      abbreviation3: "SUR",
    },
    {
      id: "0",
      code: "760",
      name: "Suriya Ərəb Respublikası",
      abbreviation2: "SY",
      abbreviation3: "SYR",
    },
    {
      id: "0",
      code: "744",
      name: "Svalbard (Şpisbergen və Yan-Mayen)",
      abbreviation2: "SJ",
      abbreviation3: "SJM",
    },
    {
      id: "0",
      code: "748",
      name: "Svazilend",
      abbreviation2: "SZ",
      abbreviation3: "SWZ",
    },
    {
      id: "0",
      code: "694",
      name: "Syerra-Leone",
      abbreviation2: "SL",
      abbreviation3: "SLE",
    },
    {
      id: "0",
      code: "682",
      name: "Səudiyyə Ərəbistanı",
      abbreviation2: "SA",
      abbreviation3: "SAU",
    },
    {
      id: "0",
      code: "762",
      name: "Tacikistan",
      abbreviation2: "TJ",
      abbreviation3: "TJK",
    },
    {
      id: "0",
      code: "764",
      name: "Tailand",
      abbreviation2: "TH",
      abbreviation3: "THA",
    },
    {
      id: "0",
      code: "834",
      name: "Tanzaniya",
      abbreviation2: "TZ",
      abbreviation3: "TZA",
    },
    {
      id: "0",
      code: "158",
      name: "Tayvan (Çinin əyaləti)",
      abbreviation2: "TW",
      abbreviation3: "TWN",
    },
    {
      id: "0",
      code: "626",
      name: "Timor-Leste",
      abbreviation2: "TL",
      abbreviation3: "TLS",
    },
    {
      id: "0",
      code: "772",
      name: "Tokelau (Yeni Zelanda)",
      abbreviation2: "TK",
      abbreviation3: "TKL",
    },
    {
      id: "0",
      code: "776",
      name: "Tonqa",
      abbreviation2: "TO",
      abbreviation3: "TON",
    },
    {
      id: "0",
      code: "768",
      name: "Toqo",
      abbreviation2: "TG",
      abbreviation3: "TGO",
    },
    {
      id: "0",
      code: "780",
      name: "Trinidad və Tobaqo",
      abbreviation2: "TT",
      abbreviation3: "TTO",
    },
    {
      id: "0",
      code: "788",
      name: "Tunis",
      abbreviation2: "TN",
      abbreviation3: "TUN",
    },
    {
      id: "0",
      code: "796",
      name: "Turk və Kaykos adaları",
      abbreviation2: "TC",
      abbreviation3: "TCA",
    },
    {
      id: "0",
      code: "798",
      name: "Tuvalu",
      abbreviation2: "TV",
      abbreviation3: "TUV",
    },
    {
      id: "0",
      code: "792",
      name: "Türkiyə",
      abbreviation2: "TR",
      abbreviation3: "TUR",
    },
    {
      id: "0",
      code: "795",
      name: "Türkmənistan",
      abbreviation2: "TM",
      abbreviation3: "TKM",
    },
    {
      id: "0",
      code: "804",
      name: "Ukrayna",
      abbreviation2: "UA",
      abbreviation3: "UKR",
    },
    {
      id: "0",
      code: "800",
      name: "Uqanda",
      abbreviation2: "UG",
      abbreviation3: "UGA",
    },
    {
      id: "0",
      code: "858",
      name: "Uruqvay",
      abbreviation2: "UY",
      abbreviation3: "URY",
    },
    {
      id: "0",
      code: "548",
      name: "Vanuatu",
      abbreviation2: "VU",
      abbreviation3: "VUT",
    },
    {
      id: "0",
      code: "862",
      name: "Venesuela",
      abbreviation2: "VE",
      abbreviation3: "VEN",
    },
    {
      id: "0",
      code: "850",
      name: "Virgin adaları (ABŞ)",
      abbreviation2: "VI",
      abbreviation3: "VIR",
    },
    {
      id: "0",
      code: "092",
      name: "Virgin adaları (Britaniya)",
      abbreviation2: "VG",
      abbreviation3: "VGB",
    },
    {
      id: "0",
      code: "876",
      name: "Vollis və Futuna adaları (Fransa)",
      abbreviation2: "WF",
      abbreviation3: "WLF",
    },
    {
      id: "0",
      code: "704",
      name: "Vyetnam",
      abbreviation2: "VN",
      abbreviation3: "VNM",
    },
    {
      id: "0",
      code: "191",
      name: "Xorvatiya",
      abbreviation2: "HR",
      abbreviation3: "HRV",
    },
    {
      id: "0",
      code: "388",
      name: "Yamayka",
      abbreviation2: "JM",
      abbreviation3: "JAM",
    },
    {
      id: "0",
      code: "392",
      name: "Yaponiya",
      abbreviation2: "JP",
      abbreviation3: "JPN",
    },
    {
      id: "0",
      code: "540",
      name: "Yeni Kaledoniya (Fransa)",
      abbreviation2: "NC",
      abbreviation3: "NCL",
    },
    {
      id: "0",
      code: "554",
      name: "Yeni Zelanda",
      abbreviation2: "NZ",
      abbreviation3: "NZL",
    },
    {
      id: "0",
      code: "300",
      name: "Yunanıstan",
      abbreviation2: "GR",
      abbreviation3: "GRC",
    },
    {
      id: "0",
      code: "887",
      name: "Yəmən",
      abbreviation2: "YE",
      abbreviation3: "YEM",
    },
    {
      id: "0",
      code: "894",
      name: "Zambiya",
      abbreviation2: "ZM",
      abbreviation3: "ZMB",
    },
    {
      id: "0",
      code: "716",
      name: "Zimbabve",
      abbreviation2: "ZW",
      abbreviation3: "ZWE",
    },
    {
      id: "0",
      code: "148",
      name: "Çad",
      abbreviation2: "TD",
      abbreviation3: "TCD",
    },
    {
      id: "0",
      code: "203",
      name: "Çexiya",
      abbreviation2: "CZ",
      abbreviation3: "CZE",
    },
    {
      id: "0",
      code: "152",
      name: "Çili",
      abbreviation2: "CL",
      abbreviation3: "CHL",
    },
    {
      id: "0",
      code: "156",
      name: "Çin",
      abbreviation2: "CN",
      abbreviation3: "CHN",
    },
    {
      id: "0",
      code: "446",
      name: "Çinin xüs. inz. r-nu Aomin (Makao)",
      abbreviation2: "MO",
      abbreviation3: "MAC",
    },
    {
      id: "0",
      code: "344",
      name: "Çinin xüs. inz. r-nu Honkonq",
      abbreviation2: "HK",
      abbreviation3: "HKG",
    },
    {
      id: "0",
      code: "860",
      name: "Özbəkistan",
      abbreviation2: "UZ",
      abbreviation3: "UZB",
    },
    {
      id: "0",
      code: "360",
      name: "İndoneziya",
      abbreviation2: "ID",
      abbreviation3: "IDN",
    },
    {
      id: "0",
      code: "400",
      name: "İordaniya",
      abbreviation2: "JO",
      abbreviation3: "JOR",
    },
    {
      id: "0",
      code: "364",
      name: "İran İslam Respublikası",
      abbreviation2: "IR",
      abbreviation3: "IRN",
    },
    {
      id: "0",
      code: "368",
      name: "İraq",
      abbreviation2: "IQ",
      abbreviation3: "IRQ",
    },
    {
      id: "0",
      code: "372",
      name: "İrlandiya",
      abbreviation2: "IE",
      abbreviation3: "IRL",
    },
    {
      id: "0",
      code: "352",
      name: "İslandiya",
      abbreviation2: "IS",
      abbreviation3: "ISL",
    },
    {
      id: "0",
      code: "724",
      name: "İspaniya",
      abbreviation2: "ES",
      abbreviation3: "ESP",
    },
    {
      id: "0",
      code: "376",
      name: "İsrail",
      abbreviation2: "IL",
      abbreviation3: "ISR",
    },
    {
      id: "0",
      code: "752",
      name: "İsveç",
      abbreviation2: "SE",
      abbreviation3: "SWE",
    },
    {
      id: "0",
      code: "756",
      name: "İsveçrə",
      abbreviation2: "CH",
      abbreviation3: "CHE",
    },
    {
      id: "0",
      code: "380",
      name: "İtaliya",
      abbreviation2: "IT",
      abbreviation3: "ITA",
    },
    {
      id: "0",
      code: "580",
      name: "Şimali Marian adaları (ABŞ)",
      abbreviation2: "MP",
      abbreviation3: "MNP",
    },
    {
      id: "0",
      code: "144",
      name: "Şri-Lanka",
      abbreviation2: "LK",
      abbreviation3: "LKA",
    },
    {
      id: "0",
      code: "004",
      name: "Əfqanıstan",
      abbreviation2: "AF",
      abbreviation3: "AFG",
    },
    {
      id: "0",
      code: "012",
      name: "Əlcəzair",
      abbreviation2: "DZ",
      abbreviation3: "DZA",
    },
  ],
  MainCurrenciesList: [
    {
      id: "0",
      code: "840",
      name: "ABŞ dolları",
      abbreviation2: null,
      abbreviation3: "USD",
    },
    {
      id: "0",
      code: "978",
      name: "Avro",
      abbreviation2: null,
      abbreviation3: "EUR",
    },
    {
      id: "0",
      code: "932",
      name: "Azərbaycan manatı",
      abbreviation2: null,
      abbreviation3: "AZN",
    },
    {
      id: "0",
      code: "784",
      name: "Dirhəm (BƏƏ)",
      abbreviation2: null,
      abbreviation3: "AED",
    },
    {
      id: "0",
      code: "268",
      name: "Gürcü larisi",
      abbreviation2: null,
      abbreviation3: "GEL",
    },
    {
      id: "0",
      code: "643",
      name: "Rusiya rublu",
      abbreviation2: null,
      abbreviation3: "RUB",
    },
    {
      id: "0",
      code: "792",
      name: "Türk lirəsi",
      abbreviation2: null,
      abbreviation3: "TRY",
    },
    {
      id: "0",
      code: "860",
      name: "Uzbekistan Somu",
      abbreviation2: null,
      abbreviation3: "UZS",
    },
    {
      id: "0",
      code: "156",
      name: "Çin yuanı",
      abbreviation2: null,
      abbreviation3: "CNY",
    },
    {
      id: "0",
      code: "826",
      name: "İngilis funt sterlinqi",
      abbreviation2: null,
      abbreviation3: "GBP",
    },
  ],
  MainUnits: [
    {
      id: "0",
      code: "796",
      name: "əd",
      abbreviation2: null,
      abbreviation3: null,
    },
    {
      id: "0",
      code: "715",
      name: "cüt",
      abbreviation2: null,
      abbreviation3: null,
    },
    {
      id: "0",
      code: "166",
      name: "kq",
      abbreviation2: null,
      abbreviation3: null,
    },
    {
      id: "0",
      code: "163",
      name: "q",
      abbreviation2: null,
      abbreviation3: null,
    },
    {
      id: "0",
      code: "112",
      name: "l",
      abbreviation2: null,
      abbreviation3: null,
    },
    {
      id: "0",
      code: "006",
      name: "m",
      abbreviation2: null,
      abbreviation3: null,
    },
  ],
  companies: [
    {
      id: 24,
      voen: "1603746681",
      name: "AL CARGO COMPANY MMC",
      shortName: "AL CARGO",
      siteName: null,
      wwName: null,
    },
    {
      id: 16,
      voen: "1404479971",
      name: "ALLEXPRESS LOJİSTİK MMC",
      shortName: "ALLEXPRESS LOJİSTİK",
      siteName: null,
      wwName: null,
    },
    {
      id: 12,
      voen: "1306102261",
      name: "APAREX MMC",
      shortName: "APAREX",
      siteName: null,
      wwName: null,
    },
    {
      id: 27,
      voen: "1700824901",
      name: "ASE ASYA AFRİKA HIZLI KARQO VE DAĞITIM ANONİM ŞİRKETİNİN AZƏRBAYCAN RESPUBLİKASINDAKI FİLİALI",
      shortName: "ASE ASYA ",
      siteName: null,
      wwName: null,
    },
    {
      id: 31,
      voen: "2005059101",
      name: "AZEXPRESS MMC",
      shortName: "AZEX",
      siteName: null,
      wwName: null,
    },
    {
      id: 40,
      voen: "9900037711",
      name: "AZƏRPOÇT MMC",
      shortName: "AZƏRPOÇT",
      siteName: null,
      wwName: null,
    },
    {
      id: 7,
      voen: "1300323371",
      name: "AZƏRİ EKSPRESS MMM",
      shortName: "FEDEX-TNT",
      siteName: null,
      wwName: null,
    },
    {
      id: 38,
      voen: "2302996972",
      name: "BABAYEV KƏRİM NAZİM OĞLU",
      shortName: "SATEX",
      siteName: null,
      wwName: null,
    },
    {
      id: 18,
      voen: "1502693421",
      name: "BERKUT EKSPRES MMC MMC",
      shortName: "BERKUT",
      siteName: null,
      wwName: null,
    },
    {
      id: 9,
      voen: "1302767131",
      name: "CAMEX MMC",
      shortName: "CAMEX",
      siteName: null,
      wwName: null,
    },
    {
      id: 25,
      voen: "1603829581",
      name: "CDEK AZERBAİJAN MMC",
      shortName: "SİDEX",
      siteName: null,
      wwName: null,
    },
    {
      id: 6,
      voen: "1102066831",
      name: "CH-GROUP MMC",
      shortName: "CH-GROUP ",
      siteName: null,
      wwName: null,
    },
    {
      id: 28,
      voen: "1702329671",
      name: "COLİBRİ EXPRESS MMC",
      shortName: "COLİBRİ",
      siteName: null,
      wwName: null,
    },
    {
      id: 35,
      voen: "2005361441",
      name: "DYNAMEX MMC",
      shortName: "DYNAMEX",
      siteName: null,
      wwName: null,
    },
    {
      id: 13,
      voen: "1400177751",
      name: "DƏRHAL LTD MMC",
      shortName: "DHL",
      siteName: null,
      wwName: null,
    },
    {
      id: 32,
      voen: "2005215081",
      name: "EXBIR LOGISTICS MMC",
      shortName: "EXBİR",
      siteName: null,
      wwName: null,
    },
    {
      id: 23,
      voen: "1603730081",
      name: "EXPERT MMC",
      shortName: "EXPERT",
      siteName: null,
      wwName: null,
    },
    {
      id: 37,
      voen: "2005966891",
      name: "FIND EXPRESS MMC",
      shortName: "FİNDEX",
      siteName: null,
      wwName: null,
    },
    {
      id: 15,
      voen: "1404405251",
      name: "FIZZA BOUTIQUE MMC",
      shortName: "FİZZA",
      siteName: null,
      wwName: null,
    },
    {
      id: 17,
      voen: "1404593661",
      name: "JET EXPRESS MMC",
      shortName: "JETEX",
      siteName: null,
      wwName: null,
    },
    {
      id: 36,
      voen: "2005606441",
      name: "JETTO MMC",
      shortName: "JETTO",
      siteName: null,
      wwName: null,
    },
    {
      id: 20,
      voen: "1504312701",
      name: "KARGOFLY MMC",
      shortName: "KARGOFLY",
      siteName: null,
      wwName: null,
    },
    {
      id: 29,
      voen: "1902010941",
      name: "LEGİON EXPRESS MMC",
      shortName: "LEGİON",
      siteName: null,
      wwName: null,
    },
    {
      id: 10,
      voen: "1305680061",
      name: "LİMAK VM MMC",
      shortName: "LİMAK",
      siteName: null,
      wwName: null,
    },
    {
      id: 21,
      voen: "1603384541",
      name: "LİNEX EXPRESS MMC",
      shortName: "LİNEX",
      siteName: null,
      wwName: null,
    },
    {
      id: 19,
      voen: "1503054331",
      name: "MOVER MMC",
      shortName: "MOVER",
      siteName: null,
      wwName: null,
    },
    {
      id: 14,
      voen: "1400226011",
      name: "NOSİLLA İNTERNEYŞENL İNK. ŞIRKƏTİNİN AZƏRBAYCAN RESPUBLİKASINDAKI FİLİALI",
      shortName: "NOSİLLA ",
      siteName: null,
      wwName: null,
    },
    {
      id: 8,
      voen: "1300619871",
      name: "PEQASUS MMC",
      shortName: "ARAMEX",
      siteName: null,
      wwName: null,
    },
    {
      id: 39,
      voen: "2903926111",
      name: "POSTALON MMC",
      shortName: "POSTALON",
      siteName: null,
      wwName: null,
    },
    {
      id: 22,
      voen: "1603671882",
      name: "QASIMZADƏ MƏHƏRRƏM ELXAN OĞLU",
      shortName: "MƏHƏRRƏM CARGO",
      siteName: null,
      wwName: null,
    },
    {
      id: 30,
      voen: "2002566311",
      name: "QUTE MMC",
      shortName: "QUTE",
      siteName: null,
      wwName: null,
    },
    {
      id: 1,
      voen: "1401576601",
      name: "RAYTECH MMC",
      shortName: "RAYTEX",
      siteName: null,
      wwName: null,
    },
    {
      id: 3,
      voen: "1005225261",
      name: "STAR EXPRESS MMC",
      shortName: "STAREX (deaktiv)",
      siteName: null,
      wwName: null,
    },
    {
      id: 34,
      voen: "2005282801",
      name: "STAREX  MMC",
      shortName: "STAREX",
      siteName: null,
      wwName: null,
    },
    {
      id: 11,
      voen: "1306001861",
      name: "SUNNY SKY MMC",
      shortName: "SUNNY",
      siteName: null,
      wwName: null,
    },
    {
      id: 26,
      voen: "1700421591",
      name: "UPS-AZ MMC",
      shortName: "UPS",
      siteName: null,
      wwName: null,
    },
    {
      id: 33,
      voen: "2005259962",
      name: "VAHİDLİ EMİL TAHİR OĞLU",
      shortName: "EYOL",
      siteName: null,
      wwName: null,
    },
    {
      id: 4,
      voen: "1005387401",
      name: "VİP LOGİSTİCS COMPANY MMC",
      shortName: "VİPEX",
      siteName: null,
      wwName: null,
    },
    {
      id: 5,
      voen: "1005945191",
      name: "İNTER EXPRESS MMC",
      shortName: "İNTEREX",
      siteName: null,
      wwName: null,
    },
    {
      id: 2,
      voen: "1004658592",
      name: "ƏLİBƏYOV GƏRAY AYAZ OĞLU",
      shortName: "ƏLİBƏYOV GƏRAY",
      siteName: null,
      wwName: null,
    },
  ],
  groups: [
    {
      id: 230,
      name: " Kamera və hissələri",
      rate: 0,
      hsCode: null,
    },
    {
      id: 431,
      name: " Kitablar",
      rate: 0,
      hsCode: null,
    },
    {
      id: 39,
      name: "Ayaqqabı kişi üçün",
      rate: 0,
      hsCode: null,
    },
    {
      id: 52,
      name: "Ayaqqabı qadın üçün",
      rate: 0,
      hsCode: null,
    },
    {
      id: 202,
      name: "Ev aksesuarları(mebel,dekor və digər)",
      rate: 0,
      hsCode: null,
    },
    {
      id: 66,
      name: "Geyim aksesuarları kişi üçün",
      rate: 0,
      hsCode: null,
    },
    {
      id: 78,
      name: "Geyim aksesuarları qadın üçün",
      rate: 0,
      hsCode: null,
    },
    {
      id: 92,
      name: "Kompüter",
      rate: 0,
      hsCode: null,
    },
    {
      id: 116,
      name: "Kosmetik vasitələr",
      rate: 0,
      hsCode: null,
    },
    {
      id: 180,
      name: "Maşın ehtiyat hissələri",
      rate: 0,
      hsCode: null,
    },
    {
      id: 146,
      name: "Məişət avadanlıqları(Böyük məişət texnikası)",
      rate: 0,
      hsCode: null,
    },
    {
      id: 159,
      name: "Məişət avadanlıqları(Kiçik məişət texnikası)",
      rate: 0,
      hsCode: null,
    },
    {
      id: 110,
      name: "Oyun konsolları",
      rate: 0,
      hsCode: null,
    },
    {
      id: 1,
      name: "Paltar, geyim",
      rate: 0,
      hsCode: null,
    },
    {
      id: 196,
      name: "Qida əlavələri",
      rate: 0,
      hsCode: null,
    },
    {
      id: 133,
      name: "Telefon",
      rate: 0,
      hsCode: null,
    },
    {
      id: 137,
      name: "Telefon(telefon üçün aksesuarlar)",
      rate: 0,
      hsCode: null,
    },
    {
      id: 214,
      name: "İdman alətləri",
      rate: 0,
      hsCode: null,
    },
  ],
  subGroups: [
    {
      id: 20,
      name: "Alt fufayka",
      rate: 15,
      hsCode: "6109909000",
    },
    {
      id: 16,
      name: "Blazer",
      rate: 15,
      hsCode: "6104390000",
    },
    {
      id: 18,
      name: "Bluz",
      rate: 15,
      hsCode: "6106909000",
    },
    {
      id: 12,
      name: "Brici",
      rate: 15,
      hsCode: "6103490000",
    },
    {
      id: 4,
      name: "Bürüncək",
      rate: 15,
      hsCode: "6102901000",
    },
    {
      id: 30,
      name: "Büstqalter",
      rate: 15,
      hsCode: "6212109000",
    },
    {
      id: 26,
      name: "Ev xələti",
      rate: 15,
      hsCode: "6107990000",
    },
    {
      id: 8,
      name: "Fırtınalıq",
      rate: 15,
      hsCode: "6102909000",
    },
    {
      id: 23,
      name: "Gecə köynəyi",
      rate: 15,
      hsCode: "6107290000",
    },
    {
      id: 6,
      name: "Gödəkçə",
      rate: 15,
      hsCode: "6102909000",
    },
    {
      id: 25,
      name: "Hamam xələti",
      rate: 15,
      hsCode: "6107990000",
    },
    {
      id: 14,
      name: "Jaket",
      rate: 15,
      hsCode: "6104390000",
    },
    {
      id: 21,
      name: "Kalson",
      rate: 15,
      hsCode: "6107190000",
    },
    {
      id: 11,
      name: "Kombinezon",
      rate: 15,
      hsCode: "6103490000",
    },
    {
      id: 31,
      name: "Korset",
      rate: 15,
      hsCode: "6212200000",
    },
    {
      id: 9,
      name: "Kostyum",
      rate: 15,
      hsCode: "6103101000",
    },
    {
      id: 17,
      name: "Köynək",
      rate: 15,
      hsCode: "6106909000",
    },
    {
      id: 7,
      name: "Küləkçə",
      rate: 15,
      hsCode: "6102909000",
    },
    {
      id: 19,
      name: "Mayka",
      rate: 15,
      hsCode: "6109909000",
    },
    {
      id: 2,
      name: "Palto",
      rate: 15,
      hsCode: "6102901000",
    },
    {
      id: 15,
      name: "Pencək",
      rate: 15,
      hsCode: "6104390000",
    },
    {
      id: 24,
      name: "Pijama",
      rate: 15,
      hsCode: "6107290000",
    },
    {
      id: 5,
      name: "Plaş",
      rate: 15,
      hsCode: "6102901000",
    },
    {
      id: 35,
      name: "Qalstuk",
      rate: 15,
      hsCode: "6215900000",
    },
    {
      id: 22,
      name: "Tuman",
      rate: 15,
      hsCode: "6107190000",
    },
    {
      id: 28,
      name: "Xizək kostyumları",
      rate: 15,
      hsCode: "6112319000",
    },
    {
      id: 3,
      name: "Yarımpalto",
      rate: 15,
      hsCode: "6102901000",
    },
    {
      id: 33,
      name: "Yaylıq",
      rate: 15,
      hsCode: "6213900000",
    },
    {
      id: 27,
      name: "Çimərlik kostyumları",
      rate: 15,
      hsCode: "6112319000",
    },
    {
      id: 32,
      name: "Çiyinbağı",
      rate: 15,
      hsCode: "6212900000",
    },
    {
      id: 38,
      name: "Önlük",
      rate: 15,
      hsCode: "6211421000",
    },
    {
      id: 37,
      name: "İdman kostyumları",
      rate: 15,
      hsCode: "6112190000",
    },
    {
      id: 29,
      name: "İstehsalat və peşə geyimi",
      rate: 15,
      hsCode: "6203421100",
    },
    {
      id: 10,
      name: "Şalvar",
      rate: 15,
      hsCode: "6103490000",
    },
    {
      id: 13,
      name: "Şort",
      rate: 15,
      hsCode: "6103490000",
    },
    {
      id: 34,
      name: "Şərf",
      rate: 15,
      hsCode: "6214900000",
    },
    {
      id: 36,
      name: "Əlcək və yarıməlcək",
      rate: 15,
      hsCode: "6216000000",
    },
  ],
  goods: {},
  totalObject: {
    goodsList: [],
    receiver: {
      birthDate: "2020-09-24T13:20:20.213Z",
      nationality: "031",
      name: "RAUF",
      surname: "QULİYEV",
      fatherName: "ZAHİD OĞLU",
      docNo: "4EDZX2V",
      dateTime: "24.09.2020",
    },
    sender: {
      carrierCompany: 24,
      country: "084",
      trackingId: "TR513226987",
      name: "Ferid Memmedov",
    },
  },
  declarations: {
    declarations: [],
    count: 0,
  },
  totalPrice: {},
  filter: {
    limit: 10,
    offset: 1,
    isFiltered: false,
    form: {},
  },
  declarationInfo: {},
  activeStep: 2,
  updateIndex: null,
  declarationNumber: "",
  loading: false,
};
